name: Setup documentation environment

inputs:
  docs_repo:
    description: "Documentation repository to use"
    required: true
    type: string
  docs_token:
    description: "Access token for the documentation repository"
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Checkout documentation repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.docs_repo }}
        path: skript-docs
        token: ${{ inputs.docs_token }}
    - uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle
    - shell: bash
      run: chmod +x ./skript/gradlew
